<?php
/**
 * Created by PhpStorm.
 * User: Usuario
 * Date: 13/10/2017
 * Time: 19:06
 */

namespace App\Extensiones;

use Codedge\Fpdf\Fpdf\Fpdf as BaseFpdf;

class Fpdf extends BaseFpdf
{
    function Cell($w, $h = 0, $txt = '', $border = 0, $ln = 0, $align = '', $fill = false, $link = '')
    {
        $txt= utf8_decode($txt);
        parent::Cell($w, $h, $txt, $border, $ln, $align, $fill, $link); // TODO: Change the autogenerated stub
    }


}